config/routes.rb
FashionApp::Application.routes.draw do
  resources :clothing_items
  
  root to: 'static_pages#home'

end

app/models/clothing_item.rb
class ClothingItem < ActiveRecord::Base
  attr_accessible :clothing_brand, :clothing_color1, :clothing_color2, :clothing_name,
                  :clothing_price, :clothing_type, :clothing_url, :photo
  
  validates   :clothing_name,  presence: true
  validates   :clothing_brand, presence: true
  validates   :clothing_color1, presence: true
  validates   :clothing_price, presence: true
  validates   :clothing_type, presence: true
  validates   :clothing_url, presence: true
                  
  has_attached_file :photo, :styles => { :small => "300x300>" }
  
  def cap_name(clothing_name)
    name_list = clothing_name.split
    name_list.each do |item|
      item.capitalize
    end
    cap_name = name_list.join(' ')
    cap_name
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clothing_items_controller.rb
class ClothingItemsController < ApplicationController
  
  def new
    @clothing_item = ClothingItem.new
  end
  
  def create
    @clothing_item = ClothingItem.new(params[:clothing_item])
    if @clothing_item.save
      redirect_to @clothing_item, :notice => "Successfully created article of clothing!"
    else
      render :action => 'new'
    end
  end
  
  def update
    @clothing_item = ClothingItem.find(params[:id])
    if @clothing_item.update_attributes(params[:clothing_item])
      redirect_to @clothing_item, :notice  => "Successfully updated article of clothing."
    else
      render :action => 'edit'
    end
  end
  
  def show
    @clothing_item = ClothingItem.find(params[:id])
  end
  
  def index
    @clothing = ClothingItem.all
  end
  
  def edit
    @clothing_item = ClothingItem.find(params[:id])
  end
  
  def destroy
    @clothing_item = ClothingItem.find(params[:id])
    @clothing_item.destroy
    redirect_to clothing_items_url, :notice => "Successfully destroy article of clothing"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/clothing_items/_form.html.erb
<div class="row">
  <%= form_for @clothing_item, :html => { :multipart => true } do |f| %>
    <div class="span4">
	  <%=f.file_field :photo %>
	</div>
    <div class="span6">
      <%= f.label :clothing_name %>
      <%= f.text_field :clothing_name %>

      <%= f.label :clothing_brand, "Clothing Brand" %>
      <%= f.text_field :clothing_brand %>

      <%= f.label :clothing_type, "Clothing Type" %>
      <%= f.text_field :clothing_type %>

      <%= f.label :clothing_color1, "Primary Color" %>
      <%= f.text_field :clothing_color1 %>

      <%= f.label :clothing_color2, "Secondary Color" %>
      <%= f.text_field :clothing_color2 %>

      <%= f.label :clothing_url, "Link to Clothing Page" %>
      <%= f.text_field :clothing_url %>

      <%= f.label :clothing_price, "Price" %>
      <%= f.text_field :clothing_price %>

      <%= f.submit "Create Clothing", class: "btn btn-large btn-primary" %>
    </div>
  <% end %>
</div>

app/views/clothing_items/_gallery_item.html.erb
<div class="span4">
  <div class="well">
	<%= link_to image_tag(clothing.photo.url(:small)), clothing %>
	<br/>
	<%= clothing.clothing_name %>
	<br/>
	<%= clothing.clothing_brand %>
  </div>
</div>
	

app/views/clothing_items/edit.html.erb
<h1>Edit Clothing</h1>

<%= render 'form' %>

<%= link_to 'Show', @clothing_item %> |
<%= link_to 'Back', clothing_items_path %>

app/views/clothing_items/index.html.erb
<h1>Clothes</h1>

<%= link_to 'New Article of Clothing', new_clothing_item_path, class: "btn btn-mini btn-info" %>
</br>
<% @clothing.each do |clothing| %>
  <div class="span4">
    <div class="well">
	  <div class="center">
  	    <%= link_to image_tag(clothing.photo.url(:small)), clothing %>
      </div>
  	  <br/>
  	  <h2><%= clothing.cap_name(clothing.clothing_name) %></h2>
  	  <h5><%= clothing.clothing_brand %></h5>
    </div>
  </div>
<% end %>

app/views/clothing_items/new.html.erb
<br/>
<br/>
<br/>
<h1>New Clothing</h1>

<%= render 'form' %>

<%= link_to 'Show', @clothing_item %> |
<%= link_to 'Back', clothing_items_path %>

app/views/clothing_items/show.html.erb
<br/>
<br/>
<br/>
<br/>
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @clothing_item.photo.url(:small) %>
  <br/>	
  <b>Name:</b>
  <%= @clothing_item.clothing_name %>
  <br/>
  <b>Brand:</b>
  <%= @clothing_item.clothing_brand %>
  <br/>
  <b>Type:</b>
  <%= @clothing_item.clothing_type %>
</p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-wrapper navbar-inverse">
  <div class="container">
    <div class="navbar-inner">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "FashionApp", root_path, class: "brand" %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="active"><%= link_to "Home", '#' %></li>
          <li><%= link_to "About", '#' %></li>
          <li><%= link_to "Contact", '#' %></li>
          <li><%= link_to "Find Clothes", clothing_items_path %></li>
        </ul>
      </div>
    </div>
  </div> 
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FashionApp</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %> 
  </head>
  <body data-spy="scroll" data-target=".bs-docs-sidebar">
    <%= render 'layouts/header' %>
    <br/>
    <br/>
    <br/>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="item active">
      <%= link_to image_tag("slide-01.jpg", alt: "Slide1"), '#' %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Match Clothes</h1>
          <p class="lead">Select a piece of clothing you own or are planning to buy, and we'll find you clothes to compliment your new outfit.</p>
          <%= link_to 'Find Clothes!', clothing_items_path, class: "btn btn-large btn-primary" %>
        </div>
      </div>
    </div>
    <div class="item">
      <%= link_to image_tag("slide-02.jpg", alt: "Slide2"), '#' %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Another example headline.</h1>
          <p class="lead">More example text.</p>
          <a class="btn btn-large btn-primary" href="#">Learn more</a>
        </div>
      </div>
    </div>
    <div class="item">
      <%= link_to image_tag("slide-03.jpg", alt: "Slide3"), '#' %>
      <div class="container">
        <div class="carousel-caption">
          <h1>One more for good measure.</h1>
          <p class="lead">One more thing of example text.</p>
          <a class="btn btn-large btn-primary" href="#">Browse gallery</a>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>